<?php

namespace Database\Seeders;

use App\Models\Produk;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nama_produk' => 'Print Hitam Putih', 'kategori_produk_id' => 2, 'harga' => 1000, 'stok' => null],
            ['nama_produk' => 'Print Warna', 'kategori_produk_id' => 2, 'harga' => 1500, 'stok' => null],
            ['nama_produk' => 'Print Kertas Buffalo', 'kategori_produk_id' => 2, 'harga' => 3000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 2x3', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 3x4', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 2R', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 4R', 'kategori_produk_id' => 2, 'harga' => 4000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 5R', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 6R', 'kategori_produk_id' => 2, 'harga' => 6000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto 10R', 'kategori_produk_id' => 2, 'harga' => 9000, 'stok' => null],
            ['nama_produk' => 'Cetak Poto Polaroid', 'kategori_produk_id' => 2, 'harga' => 900, 'stok' => null],
            ['nama_produk' => 'Fotocopy Hitam Putih', 'kategori_produk_id' => 2, 'harga' => 500, 'stok' => null],
            ['nama_produk' => 'Fotocopy Warna', 'kategori_produk_id' => 2, 'harga' => 1000, 'stok' => null],
            ['nama_produk' => 'Fotocopy Kertas Buffalo', 'kategori_produk_id' => 2, 'harga' => 1500, 'stok' => null],
            ['nama_produk' => 'Scan Dokumen', 'kategori_produk_id' => 2, 'harga' => 3000, 'stok' => null],
            ['nama_produk' => 'Ketik Konsep', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Desain Sederhana', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Desain Logo', 'kategori_produk_id' => 2, 'harga' => 10000, 'stok' => null],
            ['nama_produk' => 'Desan Banner', 'kategori_produk_id' => 2, 'harga' => 20000, 'stok' => null],
            ['nama_produk' => 'Desain Menu', 'kategori_produk_id' => 2, 'harga' => 15000, 'stok' => null],
            ['nama_produk' => 'Undangan Walimah', 'kategori_produk_id' => 2, 'harga' => 7000, 'stok' => null],
            ['nama_produk' => 'Undangan Nikah/Khitan 1000', 'kategori_produk_id' => 2, 'harga' => 1000, 'stok' => null],
            ['nama_produk' => 'Undangan Nikah/Khitan 1200', 'kategori_produk_id' => 2, 'harga' => 1200, 'stok' => null],
            ['nama_produk' => 'Undangan Nikah/Khitan 1400', 'kategori_produk_id' => 2, 'harga' => 1400, 'stok' => null],
            ['nama_produk' => 'Buku Yasin 11000', 'kategori_produk_id' => 2, 'harga' => 11000, 'stok' => null],
            ['nama_produk' => 'Buku Yasin 12000', 'kategori_produk_id' => 2, 'harga' => 12000, 'stok' => null],
            ['nama_produk' => 'Buku Yasin 13000', 'kategori_produk_id' => 2, 'harga' => 13000, 'stok' => null],
            ['nama_produk' => 'Laminating', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Press Tepi', 'kategori_produk_id' => 2, 'harga' => 4000, 'stok' => null],
            ['nama_produk' => 'Jilid', 'kategori_produk_id' => 2, 'harga' => 3000, 'stok' => null],
            ['nama_produk' => 'Jilid + Mika', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Stiker Cromo A4', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Stiker Cromo A3+', 'kategori_produk_id' => 2, 'harga' => 12000, 'stok' => null],
            ['nama_produk' => 'Stiker Vinyl A3+', 'kategori_produk_id' => 2, 'harga' => 20000, 'stok' => null],
            ['nama_produk' => 'Cetak Karton A3+', 'kategori_produk_id' => 2, 'harga' => 120000, 'stok' => null],
            ['nama_produk' => 'Print Hitam Putih A3', 'kategori_produk_id' => 2, 'harga' => 2000, 'stok' => null],
            ['nama_produk' => 'Print Warna A3', 'kategori_produk_id' => 2, 'harga' => 5000, 'stok' => null],
            ['nama_produk' => 'Fotocopy Hitam Putih A3', 'kategori_produk_id' => 2, 'harga' => 1000, 'stok' => null],
            ['nama_produk' => 'Fotocopy Warna A3', 'kategori_produk_id' => 2, 'harga' => 3000, 'stok' => null],
            ['nama_produk' => 'Buku Tulis Sidu 38', 'kategori_produk_id' => 1, 'harga' => 4000, 'stok' => 100],
            ['nama_produk' => 'Buku Tulis Kiky 38', 'kategori_produk_id' => 1, 'harga' => 4000, 'stok' => 100],
            ['nama_produk' => 'Buku Tulis Sidu 58', 'kategori_produk_id' => 1, 'harga' => 6000, 'stok' => 100],
            ['nama_produk' => 'Buku Tulis Kiky 58', 'kategori_produk_id' => 1, 'harga' => 6000, 'stok' => 100],
            ['nama_produk' => 'Buku Halus 38', 'kategori_produk_id' => 1, 'harga' => 5000, 'stok' => 50],
            ['nama_produk' => 'Buku Strimin 38', 'kategori_produk_id' => 1, 'harga' => 5000, 'stok' => 50],
            ['nama_produk' => 'Buku Gambar A4', 'kategori_produk_id' => 1, 'harga' => 6000, 'stok' => 50],
            ['nama_produk' => 'Buku Gambar A4', 'kategori_produk_id' => 1, 'harga' => 11000, 'stok' => 50],
            ['nama_produk' => 'Buku Batik A6 Paperline 100', 'kategori_produk_id' => 1, 'harga' => 7000, 'stok' => 30],
            ['nama_produk' => 'Buku Batik Quarto Paperline 100', 'kategori_produk_id' => 1, 'harga' => 12000, 'stok' => 30],

            ['nama_produk' => 'Buku Batik F4 Paperline 100', 'kategori_produk_id' => 1, 'stok' => 30, 'harga' => 20000],
            ['nama_produk' => 'Buku Batik Ekspedisi Paperline 100', 'kategori_produk_id' => 1, 'stok' => 30, 'harga' => 12000],
            ['nama_produk' => 'Pen Standard AE7 Hitam', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2000],
            ['nama_produk' => 'Pen Standard AE7 Biru', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2500],
            ['nama_produk' => 'Pen Standard AE7 Merah', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2500],
            ['nama_produk' => 'Pen Standard Techno Hitam', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2500],
            ['nama_produk' => 'Pen Lilin Quantum', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2500],
            ['nama_produk' => 'Pen Gel Zuixia HY1020 Hitam', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 3000],
            ['nama_produk' => 'Pen Gel Zuixia HY1020 Biru', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 3000],
            ['nama_produk' => 'Pen Gel Zuixia HY1020 Merah', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 3000],
            ['nama_produk' => 'Pen Gel Karakter', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 3000],
            ['nama_produk' => 'Pen Gel Tehjob', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Pen Gel Joyko', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Pen Gel Hitech', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 5000],
            ['nama_produk' => 'Pensil 2B Karakter', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2000],
            ['nama_produk' => 'Pensil 2B Staedtler', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Pensil HB Staedtler', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 7000],
            ['nama_produk' => 'Pensil 2B Fabel Castell', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 5000],
            ['nama_produk' => 'Penghapus Karakter', 'kategori_produk_id' => 1, 'stok' => 120, 'harga' => 3000],
            ['nama_produk' => 'Penghapus Joyko', 'kategori_produk_id' => 1, 'stok' => 120, 'harga' => 2000],
            ['nama_produk' => 'Penghapus Staedtler', 'kategori_produk_id' => 1, 'stok' => 120, 'harga' => 4000],
            ['nama_produk' => 'Penghapus Fabel Castell', 'kategori_produk_id' => 1, 'stok' => 120, 'harga' => 4000],
            ['nama_produk' => 'Tipe-X Cair Kenko', 'kategori_produk_id' => 1, 'stok' => 72, 'harga' => 6000],
            ['nama_produk' => 'Tipe-X Kertas Joyko', 'kategori_produk_id' => 1, 'stok' => 72, 'harga' => 5000],
            ['nama_produk' => 'Rautan Pensil Karakter', 'kategori_produk_id' => 1, 'stok' => 72, 'harga' => 2000],
            ['nama_produk' => 'Rautan Pensil Combo', 'kategori_produk_id' => 1, 'stok' => 72, 'harga' => 3000],
            ['nama_produk' => 'Lem Cair Combo', 'kategori_produk_id' => 1, 'stok' => 58, 'harga' => 3000],
            ['nama_produk' => 'Lem Cair Joyko', 'kategori_produk_id' => 1, 'stok' => 58, 'harga' => 3000],
            ['nama_produk' => 'Lem Stik Joyko', 'kategori_produk_id' => 1, 'stok' => 120, 'harga' => 2500],
            ['nama_produk' => 'Lem Bakar', 'kategori_produk_id' => 1, 'stok' => 200, 'harga' => 2500],
            ['nama_produk' => 'Lem Korea', 'kategori_produk_id' => 1, 'stok' => 36, 'harga' => 7000],
            ['nama_produk' => 'Paper Clip', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 3000],
            ['nama_produk' => 'Binder Clip 105', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 500],
            ['nama_produk' => 'Binder Clip 107', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 1000],
            ['nama_produk' => 'Binder Clip 111', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 1250],
            ['nama_produk' => 'Binder Clip 155', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 1500],
            ['nama_produk' => 'Binder Clip 200', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2000],
            ['nama_produk' => 'Binder Clip 260', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2500],
            ['nama_produk' => 'Wadah ID Card B1', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2000],
            ['nama_produk' => 'Wadah ID Card B2', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2000],
            ['nama_produk' => 'Wadah ID Card B3', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2500],
            ['nama_produk' => 'Wadah ID Card B4', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 3000],
            ['nama_produk' => 'Pelindung KTP', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2000],
            ['nama_produk' => 'Pelindung STNK', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 2500],
            ['nama_produk' => 'Label 112 TOP', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Label 103 TOP', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Buku Nota 1 Ply', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Buku Nota 2 Ply', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 6000],
            ['nama_produk' => 'Buku Kwitansi Kecil Paperline', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 4000],
            ['nama_produk' => 'Buku Kwitansi Sedang Paperline', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 6000],
            ['nama_produk' => 'Buku Kwitansi Besar Paperline', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 8000],
            ['nama_produk' => 'Buku Tabungan', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 1500],
            ['nama_produk' => 'Kertas Folio', 'kategori_produk_id' => 1, 'stok' => 200, 'harga' => 500],
            ['nama_produk' => 'Kertas HVS', 'kategori_produk_id' => 1, 'stok' => 1000, 'harga' => 200],
            ['nama_produk' => 'Kertas HVS Warna', 'kategori_produk_id' => 1, 'stok' => 1000, 'harga' => 250],
            ['nama_produk' => 'Kertas Kado', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 1500],
            ['nama_produk' => 'Kertas Manila Putih', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Manila Biru', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Karton', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],

            ['nama_produk' => 'Kertas Buffalo Putih', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Hijau Muda', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Hijau Tua', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Biru Muda', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Pink', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Merah', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Orange', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Buffalo Kuning', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 1000],
            ['nama_produk' => 'Kertas Asturo Merah', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Kuning', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Orange', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Hijau', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Biru', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Pink', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Ungu', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Hitam', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Asturo Pelangi', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 4000],
            ['nama_produk' => 'Kertas Emas Kuning', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Emas Ungu', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Emas Biru', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Emas Pink', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Merah', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Kuning', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Orange', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Hijau', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Biru', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Ungu', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Hitam', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Marmer Pink', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 3000],
            ['nama_produk' => 'Kertas Buket', 'kategori_produk_id' => 1, 'stok' => 100, 'harga' => 5000],
            ['nama_produk' => 'Kertas Hologram', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 10000],
            ['nama_produk' => 'Kertas Tisu', 'kategori_produk_id' => 1, 'stok' => 50, 'harga' => 3000],
            ['nama_produk' => 'Solasi Kado', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 1000],
            ['nama_produk' => 'Solasi Hitam', 'kategori_produk_id' => 1, 'stok' => 60, 'harga' => 2000],
            ['nama_produk' => 'Lakban Bening 12 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 6000],
            ['nama_produk' => 'Lakban Bening 24 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 8000],
            ['nama_produk' => 'Lakban Bening 45 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 10000],
            ['nama_produk' => 'Lakban Hitam 24 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 10000],
            ['nama_produk' => 'Lakban Hitam 36 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 12000],
            ['nama_produk' => 'Lakban Coklat 45 mm', 'kategori_produk_id' => 1, 'stok' => 20, 'harga' => 10500],

            ['kategori_produk_id' => 1, 'nama_produk' => 'Double Tape 6 mm', 'stok' => 20, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Double Tape 12 mm', 'stok' => 20, 'harga' => 3000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Double Tape 24 mm', 'stok' => 20, 'harga' => 5000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Double Foam 24 mm', 'stok' => 20, 'harga' => 12000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Stopmap Merah', 'stok' => 100, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Stopmap Hijau', 'stok' => 100, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Stopmap Biru', 'stok' => 100, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Stopmap Kuning', 'stok' => 100, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Amplop Coklat', 'stok' => 300, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Amplop Putih Polos 104', 'stok' => 200, 'harga' => 200],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Amplop Putih Polos 110', 'stok' => 200, 'harga' => 250],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Amplop Putih Polos 90', 'stok' => 200, 'harga' => 500],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Penggaris Bening 30 cm', 'stok' => 60, 'harga' => 3000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Penggaris Busur Butterfly', 'stok' => 60, 'harga' => 5000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Sampul Coklat Kwarto', 'stok' => 100, 'harga' => 500],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Sampul Batik Kwarto', 'stok' => 100, 'harga' => 500],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Sampul Plastik Kwarto', 'stok' => 100, 'harga' => 500],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Snowman Kecil Hitam', 'stok' => 50, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Snowman Kecil Merah', 'stok' => 50, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Snowman Kecil Biru', 'stok' => 50, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Snowman BM Black', 'stok' => 50, 'harga' => 9000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Snowman Permanent Black', 'stok' => 50, 'harga' => 9000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Joyko BM Black', 'stok' => 50, 'harga' => 6000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Spidol Joyko Permanent Black', 'stok' => 50, 'harga' => 6000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Cutter Kecil', 'stok' => 50, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Cutter Besar', 'stok' => 50, 'harga' => 4000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Isi Cutter Besar', 'stok' => 50, 'harga' => 2000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Gunting Kecil Joyko', 'stok' => 50, 'harga' => 5000],
            ['kategori_produk_id' => 1, 'nama_produk' => 'Gunting Besar Joyko', 'stok' => 50, 'harga' => 7000],
        ];

        DB::table('produks')->insert($data);

        // Produk::factory()->count(70)->create();
    }
}
